import registerComponent from 'core/registerComponent';
import ModalTrigger from 'components/ModalTrigger';
import Modal from 'components/Modal';
import ModalBody from 'components/Modal/ModalBody';
import ModalFooter from 'components/Modal/ModalFooter';
import Button from 'components/Button';
import CloseButton from 'components/CloseButton';
import Card from 'components/Card';
import CardFooter from 'components/Card/Footer';
import CardBody from 'components/Card/Body';
import CardHeader from 'components/Card/Header';
import Chat from 'components/Chat';
import ChatItem from 'components/ChatItem';
import Input from 'components/Input';
import InputBox from 'components/InputBox';
import InputError from 'components/InputBox/Error';
import Link from 'components/Link';
import Message from 'components/Message';

registerComponent(Button);
registerComponent(CloseButton);
registerComponent(Card);
registerComponent(CardBody);
registerComponent(CardFooter);
registerComponent(CardHeader);
registerComponent(Chat);
registerComponent(ChatItem);
registerComponent(Input);
registerComponent(InputBox);
registerComponent(InputError);
registerComponent(Link);
registerComponent(Message);
registerComponent(Modal);
registerComponent(ModalTrigger);
registerComponent(ModalBody);
registerComponent(ModalFooter);
